{
 "title": "Spread GoQuoteMonitor",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "DV Chain Spread 1 BTC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT ts, width_bps FROM spreads where size = 1 and ticker = 'BTC' and lp = 'DV'"
    }
   ]
  },
  {
   "title": "Enigma Spread 1BTC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT ts, width_bps FROM spreads where size = 1 and ticker = 'BTC' and lp = 'Enigma'"
    }
   ]
  },
  {
   "title": "Spreads 1 BTC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT ts, width_bps FROM spreads where size = 1 and ticker = 'BTC' and lp = 'DV'"
    },
    {
     "rawSql": "SELECT ts, width_bps FROM spreads where size = 1 and ticker = 'BTC' and lp = 'Enigma'"
    }
   ]
  },
  {
   "title": "DV Chain Spread 0.01 BTC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT ts, width_bps FROM spreads where size = 0.01 and ticker = 'BTC' and lp = 'DV'"
    }
   ]
  },
  {
   "title": "Enigma Spread 0.01 BTC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT ts, width_bps FROM spreads where size = 0.01 and ticker = 'BTC' and lp = 'Enigma'"
    },
    {
     "rawSql": "SELECT\n  ts,\n  AVG(width_bps) \n    OVER(ORDER BY ts ROWS BETWEEN 9 PRECEDING AND CURRENT ROW) \n    AS \"10mMA\"\nFROM spreads \nWHERE size = 0.01 and ticker = 'BTC' and lp = 'Enigma'\nORDER BY ts ASC;"
    }
   ]
  },
  {
   "title": "DV Chain Spread 1 ETH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT ts, width_bps FROM spreads where size = 1 and ticker = 'ETH' and lp = 'DV'"
    }
   ]
  },
  {
   "title": "Enigma Spread 1 ETH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "rawSql": "SELECT ts, width_bps FROM spreads where size = 1 and ticker = 'ETH' and lp = 'Enigma'"
    }
   ]
  },
  {
   "title": "DV Chain Spread 1 LTC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT ts, width_bps FROM spreads where size = 1 and ticker = 'LTC' and lp = 'DV'"
    }
   ]
  },
  {
   "title": "DV Chain Spread 10 AVAX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT ts, width_bps FROM spreads where size = 10 and ticker = 'AVAX' and lp = 'DV'"
    }
   ]
  },
  {
   "title": "DV Chain Spread 10 SOL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "rawSql": "SELECT ts, width_bps FROM spreads where size = 10 and ticker = 'SOL' and lp = 'DV'"
    }
   ]
  },
  {
   "title": "DV Chain Spread 100 USDC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "rawSql": "SELECT ts, width_bps FROM spreads where size = 100 and ticker = 'USDC' and lp = 'DV'"
    }
   ]
  },
  {
   "title": "DV Chain Spread 100 USDT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {
     "rawSql": "SELECT ts, width_bps FROM spreads where size = 100 and ticker = 'USDT' and lp = 'DV'"
    }
   ]
  }
 ]
}